name: rfid-rag
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - distro==1.9.0
      - duckduckgo-search==8.1.1
      - exceptiongroup==1.3.1
      - faiss-cpu==1.13.2
      - fastapi==0.128.0
      - filelock==3.20.2
      - fsspec==2025.12.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - lxml==6.0.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - openai==2.14.0
      - packaging==25.0
      - primp==0.15.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.2.0
      - sniffio==1.3.1
      - starlette==0.50.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.40.0
prefix: C:\Users\indus\anaconda3\envs\rfid-rag
